### PR TITLE
Added loading animation

### PR DESCRIPTION
**Pull request by wrestledBearOnce**
closes: #371

Removed dependency between `Fusee.Base.Imp.Blazor` and `Fusee.Engine.Imp.Graphics.Blazor`

~~TODO: Build AOT player and deploy to `$(FuseeRoot)\dis\fusee-wasm-aot-precompiled\wwwroot`~~

### CODE REVIEW

**Comment by ASPePeX** [comment]
Does this work with the DnTemplate?

**Comment by wrestledBearOnce** [comment]
> Does this work with the DnTemplate?

Should work out of the box. Just AOT the player and deliver the updated version with the template.

**Comment by ASPePeX** [comment]
This seems to leave some room for user error. Shouldn't the user then also have to ask for the loading animation to start (at the beginning of Init()). Otherwise there is suddenly a different behaviour when they build to another platform.
I recognize this is controlled by the platform player, but there is no way to do this with the DnTemplate, which is especially for inexperienced users.

**Comment by wrestledBearOnce** [comment]
Yes, you are right. I think we need to put in some work regarding the way it should be handled and the overall usability.

**Review by ASPePeX — APPROVED** [review]

**Review by ASPePeX — APPROVED** [review]

**Pull request merged**
