### PR TITLE
Fixes ImGui PointCloudPotree2 example crashes when EDL strength slider < 0.01f

### LINKED ISSUE #539: ImGui PointCloudPotree2 example crashes when EDL strength slider < `0.01f`
Line:
https://github.com/FUSEEProjectTeam/Fusee/blob/develop/Examples/Complete/PointCloudPotree2/ImGui/Core.cs#L184

Causes `OpenGL` to produce the following error message:

```
GL_INVALID_OPERATION error generated. <location> is invalid.
```

Error:

```csharp
  if (PtRenderingParams.Instance.EdlStrength != 0f)
            {
                //Render Depth-only pass
                PtRenderingParams.Instance.DepthPassEf.Active = true;
                PtRenderingParams.Instance.ColorPassEf.Active = false;

                _cam.RenderTexture = PtRenderingParams.Instance.ColorPassEf.DepthTex;
                _sceneRenderer.Render(RC);
                _cam.RenderTexture = null;

                PtRenderingParams.Instance.DepthPassEf.Active = false;
                PtRenderingParams.Instance.ColorPassEf.Active = true;
}
```

No depth pass. Therefore, no depth texture the color pass can use and expects.

Solution: do not consider EDL strength and always render a depth pass.

### PR DESCRIPTION
**Pull request by wrestledBearOnce**
Closes #539

### CODE REVIEW

**Comment by wrestledBearOnce** [comment]
Fixed. Always render a depth pass, the color pass can use. When no depth pass is being rendered, the reference to the depth texture produces an `OpenGL` `invalid operation` error

**Comment by wrestledBearOnce** [comment]
The problem seems to be the rendering to a `WritableTexture`. Seems like `SetRenderTarget(null)` works.

**Comment by wrestledBearOnce** [comment]
After Fusee's rendering is finished, `Dear ImGui` sets its own shader via `GL.SetProgram`. Unfortunately, our `RenderContext` has no knowledge about this and as `RC.CurrentShaderProgram` isn't replaced by `Dear ImGui`.

Therefore, on the next pass, no new shader is being set by Fusee inside `SetCompiledFx(IShaderHandle program)` as `_currentShaderProgram` is still the old value, https://github.com/FUSEEProjectTeam/Fusee/blob/38ddf80c4df7a49607973cbefbc1957d564637f0/src/Engine/Core/RenderContext.cs#L1346 which leads to the error, as `Dear ImGui`'s shader is still being used and as one would expect there is no uniform variable `EDLStrength` inside the GUI shader. 

When using `EDL` another shader is being set by Fusee beforehand (depth pass), which replaces the `RC.CurrentShaderProgram` variable after `ImGui` has finished, and everything works as expected.

We have two (and one very ugly) ways to fix this issue:

i) `FuseeImGui` becomes a `friend` of the `RenderContext.cs` and `Desktop.ShaderHandleImp` and replaces the `RC.CurrentShaderProgram` variable after setting its program via `GL.SetShaderProgram()` so the `RenderContext` knows it needs to bind a new shader (currently implemented)

ii) Implement a method inside `ModuleExtensionPoint` wire it inside the `RenderContext` and call this method after rendering with `Fusee.ImGui` (second method, perhaps cleaner without `friend`)

iii) The ugly one: after rendering with `Fusee.ImGui` bind the default shader `RC.SetShader(RC.DefaultShader)` and call `RC.Render(new Cube()) // <- with a scale of 0`.

@griestopf any ideas or objections against the current implementation with `i)`?

**Comment by griestopf** [comment]
> @griestopf any ideas or objections against the current implementation with i)?

No objections, if alreaday implemented and working :-).

**Review by griestopf — APPROVED** [review]
Seems a viable solution. Can see no reason to not use MakeAssemblyVisibleTo in this context.

**Pull request merged**
