### PR TITLE
float3/4.Normalize.Zero returns zero

### PR DESCRIPTION
**Pull request by wrestledBearOnce**
see #461

### CODE REVIEW

**Review by ASPePeX — COMMENTED** [review]
If I remember correctly intN.Normalize() to return a floatN, instead of a intN approximation, was deliberate. But it is as matter of definition and should be discussed at our next meeting.

**Comment by wrestledBearOnce** [comment]
> If I remember correctly intN.Normalize() to return a floatN, instead of a intN approximation, was deliberate. But it is as matter of definition and should be discussed at our next meeting.

imoh `intN(1,1,1)` should not normalize to `intN(0,0,0)` due to missing decimals.

**Comment by ASPePeX** [comment]
I agree, that is why we didn't drop the decimal.

**Review by ASPePeX — APPROVED** [review]
My fault, didn't see the intX.Normalize() changes were reversed.

**Pull request merged**
