### PR TITLE
WebAsm Imps, including new protobuf-net and SharpFontManaged lib

### PR DESCRIPTION
**Pull request by wrestledBearOnce**
MERGE https://github.com/FUSEEProjectTeam/Fusee/pull/162 FIRST!

### CODE REVIEW

**Comment by wrestledBearOnce** [comment]
TODO:
- [ ] Fix asset management for WebAsm (collect and copy all assets)
- [ ] Figure out why the CI refuses to build when it actual does build locally for me and @RedImp1470

**Comment by ASPePeX** [comment]
The CI only builds Release-Desktop and Release-Android, there shouldn't be any WebAsm projects in these build configuations.

**Comment by wrestledBearOnce** [comment]
> 
> 
> SharpFontManaged is checked in without proper .gitignore settings, the `.vs` folder is just user settings and cache.
> Also imo I don't think we should be including the source code for it in our main repo, especially when we use it as a Reference instead of a ProjectReference.
> If we have any changes for it I would like it to build from a fork.

Yeah, let's do that.

**Comment by wrestledBearOnce** [comment]
> 
> 
> protobuf-net should be pulled from nuget if possible. I didn't see 3.0.0-alpha.125 but here is 3.0.0-alpha.128.

This is the self-built version which works with the monolinker. The protobuf-net nuget version breaks everything.

**Comment by ASPePeX** [comment]
Ahhh, right I forgot. Disregard that change request.

**Comment by wrestledBearOnce** [comment]
This should theoretically be mergable. Unfortunately it breaks ALL *.fus IO until v2 of serialization is done and merged. Waiting for @griestopf

**Comment by wrestledBearOnce** [comment]
Added examples
- Simple Deferred not working (*.fus file is missing, deferred impls needs to be checked)
- BoneAnimation not working (*.fus file is missing)
- UI is not working (we can't load jpegs via SkiaSharp, yet)

**Comment by wrestledBearOnce** [comment]
TODO:

- [ ] 2nd test of all examples (@ASPePeX @griestopf @RedImp1470 ?)
- [ ] documentation (serialize and webasm)

**Pull request merged**
