### PR TITLE
Feature/OpenTK4

### PR DESCRIPTION
**Pull request by ASPePeX**
Update to latest OpenTK Version

### CODE REVIEW

**Comment by griestopf** [comment]
Did you check if 
1. gamepad access works with the changes
2. the blender export Add-on still works with the generated Python code after changing the protobuf version
?

**Comment by ASPePeX** [comment]
> 1. gamepad access works with the changes

Since you asked I checked a little bit deeper into it that before and found that the button assignments were not correct. This is now fixed.

> 2. the blender export Add-on still works with the generated Python code after changing the protobuf version

Yes, the Blender addon works. Loading .fus assets back into Fusee works as well.

**Comment by griestopf** [comment]
Looks good.

**Review by griestopf — APPROVED** [review]

**Review by griestopf — COMMENTED** [review]
Approved!

**Pull request merged**
