### PR TITLE
Feature/serialization v2

### LINKED ISSUE #197: Serialization V2

### PR DESCRIPTION
**Pull request by wrestledBearOnce**
TODO: Move ShaderEffect.cs to F.E. Common after changes of #130 are merged.

Closes #197.

Blocked-by #92

### CODE REVIEW

**Comment by wrestledBearOnce** [comment]
I've just realized there are missing conversion methods, namely:
- FusAnimation
- FusAnimationTracks
- FusXForm
- FusXFormText
- FusCanvasTransform
- FusRectTransform

going to implement them right away!

**Comment by wrestledBearOnce** [comment]
We do have a bug inside `DoVisitComponents(TNode node)`. It seems that one can't alter any `TComponents` during runtime because it's iterated in such a way, that any modification during iteration leads to an exception. see: https://github.com/FUSEEProjectTeam/Fusee/blob/feature/serialization_v2/src/Xene/Visitor.cs#L513

 @griestopf

**Comment by wrestledBearOnce** [comment]
\o/
I'm hesitant to merge, yet, because all *.fus files are obsolete after this!

**Comment by wrestledBearOnce** [comment]
@ASPePeX 
```bash
Fusee.Tools.CmdLine -> /home/runner/work/Fusee/Fusee/bin/Release/Tools/CmdLine/fusee.dll
  /bin/sh: 2: /tmp/tmp17a26026404a4e4d96e2f1ffec1ba784.exec.cmd: /home/runner/work/Fusee/Fusee/bin/Release/Tools/CmdLine/fusee.exe: not found
/home/runner/work/Fusee/Fusee/src/Tools/fuseeCmdLine/Fusee.Tools.CmdLine.csproj(79,5): warning MSB3073: The command ""/home/runner/work/Fusee/Fusee/bin/Release/Tools/CmdLine/fusee.exe" protoschema -o "/home/runner/work/Fusee/Fusee/src/Tools/BlenderScripts/addons/io_export_fus/proto_src/Scene.proto"" exited with code 127.
```

while building for ubuntu. I'm not sure this should happen, or that it should even build an *.exe.

**Comment by ASPePeX** [comment]
Yes, that part doesn't work on linux yet. I'm waiting for the codebase to stabilize before messing with the build again.

**Pull request merged**
